services:
  html-css-js:
    image: html-css-js_c
    build:
      dockerfile: Dockerfile.dev
    container_name: html-css-js
    restart: unless-stopped
    ports:
      - ${NGINX_PORT_OUT}:${NGINX_PORT}
    volumes:
      - ./src:/usr/share/nginx/html:ro
    